src/main/java/com/sonic/agent/tests/android/AndroidTestTaskBootThread.java

之前没注意，产生的一个bug。  
假如一个测试套件中，有三个case，这三个case都用同一台设备跑，且每一条的case都超过最长等待时间（现在是1小时）。  
那么现在case1跑了超过1小时了，case2，case3超时，进入下面的if逻辑，发送消息并return：  
```java
if (wait >= 6 * 10) {
androidStepHandler.waitDeviceTimeOut();
androidStepHandler.sendStatus();
return;
} else {
Thread.sleep(10000);
}
```
但是以为上面的代码更外层有`try...catch...finally`，所以即便是`return`，也依然会执行`finally`的逻辑，而`finally`中的`AndroidDeviceLocalStatus.finish(udId)`会释放设备。如果这之后case1还在运行，同时进来case4，也是用同一台设备，那么case4执行`AndroidDeviceLocalStatus.startTest(udId)`将会返回true，造成设备重复占用。

🐛： 修复等待超时后，仍然有任务在执行，但设备会被释放的bug

---

src/main/java/org/cloud/sonic/agent/tests/TaskManager.java
src/main/java/org/cloud/sonic/agent/tests/android/AndroidRunStepThread.java
src/main/java/org/cloud/sonic/agent/tests/common/RunStepThread.java
src/main/java/org/cloud/sonic/agent/tests/ios/IOSRunStepThread.java
src/main/java/org/cloud/sonic/agent/tools/AgentTool.java
src/main/java/org/cloud/sonic/agent/tools/LogTool.java
src/main/java/org/cloud/sonic/agent/websockets/AndroidWSServer.java
src/main/java/org/cloud/sonic/agent/websockets/IOSWSServer.java

中断没有用`thread.interrupt();`设置标志位，是因为如果线程处于sleep（类似强制等待的功能），调用`thread.interrupt();`后，会将线程唤醒，唤醒后的线程查看interrupted如果为true则抛出异常，抛出异常后interrupted又变为true了，所以使用自定义的标记位。

🐛: 更改debug下的中断策略

---

src/main/java/org/cloud/sonic/agent/tests/TaskManager.java
src/main/java/org/cloud/sonic/agent/tests/android/OutputSocketThread.java

问题来源：https://sonic-cloud.wiki/d/288  
还有个内存突增的问题没排查出来，但觉得跟泄露是两回事，先提这个

🐛: 修复录屏内存泄露

---

src/main/java/org/cloud/sonic/agent/automation/AndroidStepHandler.java

在Flutter应用上，输入框输入文本，如果使用Android Driver，以下方式无法输入文本：
`findEle(selector, pathValue).sendKeys(keys);`
需要切换为以下方式：
`new Actions(androidDriver).sendKeys(findEle(selector, pathValue),keys).perform();`

feat:增加输入框控件输入文本方法-sendKeysByActions

---

src/main/java/org/cloud/sonic/agent/automation/AndroidStepHandler.java

cssSelectorAndText Value改为逗号分隔，防止和全局参数多个值时产生冲突

refactor:cssSelectorAndText Value改为逗号分隔

---

src/main/java/org/cloud/sonic/agent/automation/AndroidStepHandler.java

场景：
安卓端目前已实现的操作步骤只有ele1滑动到ele2的滑动方式，Appium滑动方法也只有基于点到点的滑动，缺少高级滑动方法(要实现复杂列表搜索需要写大量判断步骤)，目前不足以覆盖列表滑动搜索控件需求。
参考：
android端UIAutomator控件定位方式用于处理列表搜索控件功能
https://appium.io/docs/en/writing-running-appium/tutorial/swipe/android-simple/
处理：
由于目前基于Appium获取的控件与基于UIAutomator的UISelector获取的控件无法相互转换，所以不对UIAutomator的语法再做转换，直接暴露语法输入给用户，相关UIAutomator语法直接由用户实现。
例子：
滑动列表中搜索定位包含"商品"文本的View
new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(new UiSelector().textContains("商品"))

feat: 新增通过UIAutomator方法(仅限Android端/UIAutomator2引擎)定位控件元素

---

src/main/java/org/cloud/sonic/agent/tests/AndroidTests.java
src/main/java/org/cloud/sonic/agent/tests/IOSTests.java
src/main/java/org/cloud/sonic/agent/tests/TaskManager.java

+ "-" + udId(设备序列号)
**填写PR内容：**
解决多设备执行是串行而不是并行问题，原因是由于agent限制了相同的结果rid只能有一个执行

fix: 将原来agent只能有一个结果rid执行，改为agent只能有一个结果rid

---

src/main/java/org/cloud/sonic/agent/tests/ios/IOSRunStepThread.java

**填写PR内容：**
此处可能是遗漏，iOSRunStepThread的handleDes每次是新建，会出现条件判断不执行的问题。改为复用同一个HandleDes对象即可。

fix:修复iOS步骤执行时handleDes未使用同一个对象导致条件判断失效的问题

---

src/main/java/org/cloud/sonic/agent/tests/AndroidTests.java
src/main/java/org/cloud/sonic/agent/tests/IOSTests.java
src/main/java/org/cloud/sonic/agent/tests/SuiteListener.java
src/main/java/org/cloud/sonic/agent/tests/TaskManager.java

**填写PR内容：**
你好，实际使用用例分发执行过程中发现，多设备下分发套件用例，当设备上的用例不均时，先完成的设备会将runningTestsMap中的rid给remove，导致在同一agent上的其它设备会进入下面这个判断：
套件就会直接结束。造成用例执行不完全的现象，并且在运行结果出一直显示运行中
修复方法：将runningTestsMap中的key由rid改为rid-udId，这样remove的时候只会remove当前设备的key，而其它设备不会造成干扰。在实践中已经做了修改，用例执行顺利完成，无遗漏现象。

fix:修复runningTestsMap的key为rid导致条件判断失效遗漏用例执行的问题

---

src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java
src/main/java/org/cloud/sonic/agent/tests/handlers/IOSStepHandler.java

> 
1、长按元素的方法我发现有时候并不生效，比如在长按桌面的某个程序希望它弹出一些菜单选择项时。将其长按的位置移动到元素中心位置，可解决该问题。
2、swipeByDefinedDirection 方法有两个参数：slideDirection和distance。slideDirection表示方向，支持上下左右，distance为滑动的距离(像素)。

feat:修改longPress 位置为元素中心;增加swipeByDefinedDirection方法,以屏幕中心为起始 位置,根据自定义像素距离,支持上滑/下滑/左滑/右滑

---

src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java
src/main/java/org/cloud/sonic/agent/tests/handlers/IOSStepHandler.java

> 
Agent增加支持：断言验证(不相等)的类型，扩充相关指令。
另外3个断言的执行输出，也丰富了一下内容，更加清晰一点。
社区有相关需求反馈，[校验断言中希望可以加个【不相等】的断言，只有不包含不太够用](https://sonic-cloud.wiki/d/2689)
我们内部的项目也有相关的需求，尝试实现了一下。

实现断言验证(不相等)的agent逻辑，并丰富另外三个断言类型的输出

---

src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java
src/main/java/org/cloud/sonic/agent/tests/handlers/AssertUtil.java
src/main/java/org/cloud/sonic/agent/tests/handlers/IOSStepHandler.java

> 
需求场景，给定的元素定位方式，在当前的视图树中，可能查找到多个。例如listVIew中的列表item，每个item的元素id均相同，即可通过这种方式，验证列表元素的个数。
数量比较目前支持五种方式：
本次pr覆盖的场景
运行效果：
运行效果

feat:支持断言目标元素存在的数量

---

src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java

> 
原来的`webElementScrollToView`参数传递部分有些问题，导致元素一直无法找到。
修改下参数的传递逻辑。

fix:修复webElementScrollToView方法，获取控件信息传参错误导致的元素一直无法找到。

---

src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java
src/main/java/org/cloud/sonic/agent/tests/handlers/IOSStepHandler.java

> 
需求场景，在长列表的场景下，通常需要滑动让某个元素可见，才可以进行后续的操作。但由于屏幕分辨率的问题，滑动的距离和次数很难把握。
“滚动到指定元素可见的能力”，可以允许用户指定方向，最大滑动的次数，以及目标元素。agent层会尝试每次滑动屏幕三分之一的高度，并查找目标元素是否可见，不可见则循环，直到目标元素出现，或者滑动的次数到最大的次数。
UI效果如下：

feat:Android与iOS端长列表的场景下，实现“滚动到指定元素”可见的能力

---

src/main/java/org/cloud/sonic/agent/bridge/android/AndroidDeviceBridgeTool.java

> 
发现部分高版本机器(Android12，13)上，无法正确获取到当前Activity，经排查发现执行
```
adb shell dumpsys  window displays
```
存在mCurrentFocus=null的场景，按现有逻辑去截取当前Activity会出现错乱。

fix:修复adb shell dumpsys  window displays获取到多个mCurrentFocus时，无法正确得到当前Activity

---

src/main/java/org/cloud/sonic/agent/bridge/ios/SibTool.java

> 
[社区反馈](https://sonic-cloud.wiki/d/3384-v260iosmonkey)
问题原因：
获取安装包列表时会解析出一个null对象到`getAppList`，导致方法异常：
```
public static List<String> getAppList(String udId) {
return getAppList(udId, null).stream().map(e->e.getString("bundleId")).collect(Collectors.toList());
}
```

fix:修复iOS类似Monkey能力的随机事件时报错

---

src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java
src/main/java/org/cloud/sonic/agent/tests/handlers/IOSStepHandler.java

> 
[社区反馈问题](https://sonic-cloud.wiki/d/3391-cny-content-desc)
增加获取控件属性到自定义变量的能力，支持Android,iOS,Poco类型。

feat:增加获取控件属性到自定义变量的能力

---

src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidPermissionExtractor.java
src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidPermissionItem.java
src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java

> 
Android端6.0之后的系统，部分敏感权限系统强制要求运行时动态授权，会对用例执行产生干扰，需要自己处理。
参考Appium的启动参数`autoGrantPermissions`的实现原理，在sonic中补齐相关能力。
[appium-adb中相关实现](https://github.com/appium/appium-adb/blob/master/lib/helpers.js#L477)

feat:Android端添加“自动授权应用”指令，指定包名后自动赋予被测应用运行时所需权限，不再出现运行时权限弹窗，避免对用例执行的干扰

---

src/main/java/org/cloud/sonic/agent/bridge/android/AndroidDeviceBridgeTool.java

> 
https://registry.npmmirror.com/-/binary/chromedriver/86.0.4240.22/
当webview版本<=86时，google官方未提供M1架构对应的chromeDriver，这里修复，改为固定使用chromedriver_mac64.zip

fix:修复m1系统webview版本小于87时无法下载chromeDriver的问题

---

src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java
src/main/java/org/cloud/sonic/agent/tests/handlers/IOSStepHandler.java
src/test/java/org/cloud/sonic/agent/tests/handlers/TextHandlerTest.java

> 
例如上图一个城市选择器，使用控件定位可以获取到元素对象，但是滑动终点无法确定，考虑使用元素属性获取坐标后使用自定义脚本计算出滑动的起点、终点坐标，再使用坐标滑动方法操作，发现坐标系的控件参数化无效，因此增加这个参数化的代码

feat: 自动化步骤中坐标相关操作的控件元素也可以使用参数化&安卓获取控件属性时可直接获取中心坐标值

---

pom.xml
src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java
src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidTouchHandler.java

> 
- 原pr：https://github.com/SonicCloudOrg/sonic-agent/pull/447
1. 对接driver新增uia模式的拖拽（drag）、touchAction
2. 对原来swipe相关方法中出现`拖拽`词语的进行纠正为`滑动`
- 考虑有些拖拽目标定位是在长按图标之后才会出现的，所以将拖拽3个步骤拆成独立步骤，经过测试长按之后接拖拽事件也是可以的
1. 3个模式下，drag操作均符合预期
2. motionEvent(即touchAction)中down、up操作基本符合预期
4. adb模式下，move motionEvent符合预期，uia和sonic模式会出现卡顿，即划线过程中会出现一次停顿 
5. motionEvent，在手机桌面上操作图片拖拽，有可能需要执行两次move操作，图标才会移动，可能是机型差异，而在微信小程序菜单中则不会出现这个问题

feat: `Android`自动化测试步骤中新增拖拽操作以及拖拽动作拆分的三个独立事件操作

---

src/main/java/org/cloud/sonic/agent/bridge/android/AndroidSupplyTool.java

fix: 整理代码并解决调用远程ADB持续发送命令会被阻塞的问题 

---

src/main/java/org/cloud/sonic/agent/transport/TransportClient.java
src/main/java/org/cloud/sonic/agent/websockets/AndroidWSServer.java
src/main/java/org/cloud/sonic/agent/websockets/IOSWSServer.java

> 
https://github.com/SonicCloudOrg/sonic-client-web/pull/296

feat: 在获取元素页面中快捷测试元素定位是否可以定位并点击

---

src/main/java/org/cloud/sonic/agent/tools/EnvCheckTool.java

fix: 修复了在启动agent服务检测环境时，如果项目路径或者相关依赖路径名称存在空格，则会报错的问题
