SonicCloudOrg/sonic-agent

src/main/java/com/sonic/agent/bridge/android/AndroidDeviceBridgeTool.java, src/main/java/com/sonic/agent/bridge/ios/TIDeviceTool.java, src/main/java/com/sonic/agent/netty/NettyClient.java, src/main/java/com/sonic/agent/netty/NettyClientHandler.java, src/main/java/com/sonic/agent/tests/android/AndroidTemperThread.java
=> 🐛：修复server端断线重连后设备状态丢失问题

config/application-prod.yml, src/main/resources/application-dev.yml
=> [优化]: 更改控制台日志信息

src/main/java/com/sonic/agent/websockets/AndroidWSServer.java, src/main/java/com/sonic/agent/websockets/IOSWSServer.java
问题见：https://sonic-cloud.wiki/d/68-agent
=> 退出太快导致`exit`空指针，session没有close的问题

src/main/java/com/sonic/agent/tests/android/InputSocketThread.java, src/main/java/com/sonic/agent/tests/android/OutputSocketThread.java
效果见：https://sonic-cloud.wiki/d/85 最佳回复
=> 🍺: 优化远控时CPU占用

src/main/java/org/cloud/sonic/agent/websockets/AudioWSServer.java, src/main/resources/application-dev.yml, src/main/resources/application.yml
=> 修复远程音频粘包问题

src/main/java/org/cloud/sonic/agent/bridge/android/AndroidDeviceBridgeTool.java, src/main/java/org/cloud/sonic/agent/tests/android/AndroidBatteryThread.java
=> 监听加上设备电量第一期

src/main/java/org/cloud/sonic/agent/tests/TaskManager.java
from: https://sonic-cloud.wiki/d/288/34
=> 🐛: fix null pointer bug

src/main/java/org/cloud/sonic/agent/automation/AndroidStepHandler.java
activity验证改到验证操作栏目中，使用全局参数进行逻辑处理。
=> feat: 添加验证Activity方法

src/main/java/org/cloud/sonic/agent/transport/TransportClient.java
重连成功后还一直在尝试Server disconnected. Retry in 10s...
=> websocket连接关闭时增加if(TransportWorker.client == this) { 判断

src/main/java/org/cloud/sonic/agent/tools/EnvCheckTool.java
=> feat: remove_appium_text2

pom.xml, src/main/java/org/cloud/sonic/agent/automation/AndroidStepHandler.java
=> feat:add poco touch true coordinate get

src/main/java/org/cloud/sonic/agent/bridge/android/AndroidDeviceBridgeTool.java
**填写PR内容：**
2.0.0-beta版本，切换webview时报异常，详见sonic社区提问: https://sonic-cloud.wiki/d/1786-200-betawebview
=> fix: 切换webview报错问题(https://sonic-cloud.wiki/d/1786-200-betawebview)

pom.xml, src/main/java/org/cloud/sonic/agent/automation/AndroidStepHandler.java, src/main/java/org/cloud/sonic/agent/automation/IOSStepHandler.java, src/main/java/org/cloud/sonic/agent/bridge/android/AndroidDeviceBridgeTool.java, src/main/java/org/cloud/sonic/agent/bridge/android/AndroidSupplyTool.java, src/main/java/org/cloud/sonic/agent/bridge/ios/SibTool.java, src/main/java/org/cloud/sonic/agent/tools/SGMTool.java, src/main/java/org/cloud/sonic/agent/websockets/AndroidWSServer.java, src/main/java/org/cloud/sonic/agent/websockets/IOSWSServer.java
=> feat 2.0.0 release

src/test/java/org/cloud/sonic/agent/android/MockStepDebugTest.java
=> feat:add local agent step debug or test

pom.xml, src/test/java/org/cloud/sonic/agent/android/MockStepDebugTest.java
=> feat:add mock server send step json to agent and step run

pom.xml, src/main/java/org/cloud/sonic/agent/aspect/IteratorAspect.java, src/main/java/org/cloud/sonic/agent/aspect/IteratorCheck.java, src/main/java/org/cloud/sonic/agent/automation/AndroidStepHandler.java, src/main/java/org/cloud/sonic/agent/automation/IOSStepHandler.java, src/main/java/org/cloud/sonic/agent/common/models/HandleContext.java, src/main/java/org/cloud/sonic/agent/tests/handlers/ElseHandler.java, src/main/java/org/cloud/sonic/agent/tests/handlers/ElseIfHandler.java, src/main/java/org/cloud/sonic/agent/tests/handlers/IfHandler.java, src/main/java/org/cloud/sonic/agent/tests/handlers/NoneConditionHandler.java, src/main/java/org/cloud/sonic/agent/tests/handlers/StepHandlers.java, src/main/java/org/cloud/sonic/agent/tests/handlers/WhileHandler.java, src/test/java/org/cloud/sonic/agent/android/MockStepDebugTest.java, src/test/java/org/cloud/sonic/agent/aspect/MockPocoParamTest.java, src/test/java/org/cloud/sonic/agent/aspect/TestAop.java, src/test/resources/MockIfData.json, src/test/resources/MockIteratorAndroid.json, src/test/resources/MockIteratorAttr.json
=> feat:Dev/iterator

src/main/java/org/cloud/sonic/agent/aspect/IteratorAspect.java, src/main/java/org/cloud/sonic/agent/automation/AndroidStepHandler.java, src/main/java/org/cloud/sonic/agent/automation/IOSStepHandler.java
=> feat:add iOS iterator

src/main/java/org/cloud/sonic/agent/tests/android/AndroidTestTaskBootThread.java, src/main/java/org/cloud/sonic/agent/tests/ios/IOSTestTaskBootThread.java
=> fix: 修复测试套件执行异常时，上报了2次结果状态的问题

src/main/java/org/cloud/sonic/agent/bridge/android/AndroidDeviceBridgeTool.java, src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java
=> fix: 解决用例中打开不存在的应用也不报错的问题

src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java, src/main/java/org/cloud/sonic/agent/tests/handlers/IOSStepHandler.java, src/main/java/org/cloud/sonic/agent/tests/script/GroovyScriptImpl.java, src/main/java/org/cloud/sonic/agent/tests/script/PythonScriptImpl.java, src/main/java/org/cloud/sonic/agent/tests/script/ScriptRunner.java
> 
优化自定义脚本无法强制停止的问题，并支持python脚本执行过程中输出（注：要看到此效果python输出语句要注意及时flush输出）
=> fix: force stop has no effect on running script

src/main/java/org/cloud/sonic/agent/tests/script/GroovyScriptImpl.java
> 
自定义Groovy Script 返回空值时不再输出脚本执行结果提示消息
=> fix: omit script result output when GroovyScript return null

src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java, src/main/java/org/cloud/sonic/agent/tests/handlers/IOSStepHandler.java, src/main/java/org/cloud/sonic/agent/tests/handlers/StepHandlers.java
=> fix: 修复公共步骤嵌套不执行

src/main/java/org/cloud/sonic/agent/bridge/android/AndroidDeviceBridgeTool.java, src/main/java/org/cloud/sonic/agent/tools/EnvCheckTool.java
=> feat: 优化本地资源检查，支持内置adb

src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java, src/main/java/org/cloud/sonic/agent/tests/handlers/IOSStepHandler.java
> 
部分移动端Web场景下，发现H5页面的输入框无法直接输入，需要先获取焦点。
排查发现Android端已实现类似能力，但iOS端未对齐，一起补充上。
=> feat: H5端与iOS端，实现先获取焦点，再输入文本的能力，对齐Android端

src/main/java/org/cloud/sonic/agent/bridge/ios/SibTool.java, src/main/java/org/cloud/sonic/agent/tests/handlers/IOSStepHandler.java
=> fix: 优化图片识别后根据坐标点击屏幕位置的准确

src/main/java/org/cloud/sonic/agent/bridge/ios/SibTool.java, src/main/java/org/cloud/sonic/agent/tests/handlers/IOSStepHandler.java
=> feat: 添加iOS 类似Monkey能力的随机事件

src/main/java/org/cloud/sonic/agent/bridge/android/AndroidDeviceBridgeTool.java, src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java, src/main/java/org/cloud/sonic/agent/websockets/AndroidWSServer.java
> 
uninstall方法有返回值，会明确卸载操作是否成功。
=> fix:增加卸载安装包方法的返回值校验，应用包名不存在或错误时，认定步骤失败

pom.xml, src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java, src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidTouchHandler.java, src/main/java/org/cloud/sonic/agent/transport/TransportClient.java, src/main/java/org/cloud/sonic/agent/websockets/AndroidWSServer.java, src/main/java/org/cloud/sonic/agent/websockets/IOSWSServer.java
> 
长按，滑动，点击等触控操作，目前sonci提供了基于adb以及基于sonic-android-apk的两种模式，
本次pr新增加第三种，基于uiautomatro2的模式。
=> feat:Android端增加第三种触控模式，基于uiautomator2

src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidTouchHandler.java, src/test/java/org/cloud/sonic/agent/tests/handlers/AndroidTouchHandlerTest.java
> 
当前基于SonicAPK 的滑动模式，是触发了一个touchMove事件，瞬间从起始点到目标点，使用感官上比较生硬。
本次pr通过lambda表达式实现了一个插值表达式，每隔5ms触发一次滑动，线性移动到目标位置，更符合人的感官。
同时把滑动的时间参数化，便于后续统一在前端UI层指定滑动操作的时间。
另外之前基于adb的方式，滑动默认是300ms，相对比较短，容易触发fling效果，本次修改统一3种滑动操作，默认都是500毫秒。
=> feat:基于SonicAPK的滑动，实现线性滑动的效果，避免过渡太生硬

src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java, src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidTouchHandler.java
> 
[社区反馈问题](https://sonic-cloud.wiki/d/3404-cny)
安卓端滚动到，耗时改为1000毫秒，其他的默认情况下依然设置为500毫秒
=> fix:修复Android上滚动到元素可见操作，滑动过快的问题

src/main/java/org/cloud/sonic/agent/bridge/android/AndroidDeviceBridgeTool.java, src/main/java/org/cloud/sonic/agent/common/maps/ChromeDriverMap.java
=> feat: 适配chromeDriver121-126的版本，并替换下载地址链接

src/main/java/org/cloud/sonic/agent/bridge/ios/CompareVersionUtil.java, src/main/java/org/cloud/sonic/agent/bridge/ios/SibTool.java, src/test/java/org/cloud/sonic/agent/bridge/ios/CompareVersionUtilTest.java
=> 【feature】SibTool增加一个方法，用于判断手机ios系统是否>=17

src/main/java/org/cloud/sonic/agent/bridge/ios/SibTool.java
=> fix: ios设备获取webview时报空指针错误

src/main/java/org/cloud/sonic/agent/bridge/android/AndroidSupplyTool.java
=> fix:修复无法停止性能监控

src/main/java/org/cloud/sonic/agent/bridge/android/AndroidDeviceThreadPool.java, src/main/java/org/cloud/sonic/agent/bridge/ios/IOSDeviceThreadPool.java, src/main/java/org/cloud/sonic/agent/bridge/ios/SibTool.java
> 
@ Bean should not return void
=> refactor: @Bean should not return void
